Update ceilometer logrotate config for Juno
Logrotate config file has changed for Juno. This creates duplicate
logrotate configs and results in the following errors:
/etc/cron.daily/logrotate:
error: ceilometer-common:1 duplicate log entry for
/var/log/ceilometer/ceilometer-agent-compute.log

You will also need to remove the duplicate logrotate file created by
puppet prior to this change:
rm /etc/logrotate.d/ceilometer

Change-Id: Idd5563d76299a32432b99ba10049503dbe3faded